### ISSUE TITLE
./onvm/go.sh 1,2,3 1 -s stdout -a 0x7f000000000  stop running

### ISSUE THREAD

**Issue by XinShuYang** [sdnfv/openNetVM#100]
## Bug Report

**Current Behavior**
I try to build a mtcp container on ONVM, but the mmap function failed. I found this issue has been mentioned in mtcp onvm install guides. But when I try this go.sh command, it stops running at "APP: Stats verbosity level = 1" .(in screenshots)
<img width="909" alt="Screen Shot 2019-04-12 at 10 06 19 AM" src="https://user-images.githubusercontent.com/25102428/56043157-b046d900-5d0a-11e9-801f-face398b7bfa.png">

**Steps to reproduce**
cd /root/openNetVM
./onvm/go.sh 1,2,3 1 -s stdout -a 0x7f000000000

**Environment**
- OS:  Ubuntu 14.04.1 LTS (CloudLab 220g2)
- onvm version:  latest ONVM develop branch

**Possible Solution**
I try to add a cpu mask, and then it can work.
./onvm/go.sh 1,2,3 1 0xF8 -s stdout -a 0x7f000000000

**Additional context/Screenshots**
<img width="717" alt="Screen Shot 2019-04-12 at 10 07 50 AM" src="https://user-images.githubusercontent.com/25102428/56043253-e1bfa480-5d0a-11e9-9e35-d98f25baae86.png">

**Comment by koolzz** [comment]
To confirm, does this `./onvm/go.sh 1,2,3 1 0xF8 -s stdout -a 0x7f000000000` work fine? The mtcp examples don't have the updated onvm_mgr args, the cpu mask for NFs is a required arg. I'll submit a quick pr to mtcp to fix that.

**Comment by XinShuYang** [comment]
./onvm/go.sh 1,2,3 1 0xF8 0 -s stdout -a 0x7f000000000  doesn't work.  I have tested the epserver in opennetvm-dev latest version and it works. (using ./onvm/go.sh 1,2,3 1 0xF8 -s stdout -a 0x7f000000000)

**Comment by koolzz** [comment]
Oh sorry it should be ./onvm/go.sh 1,2,3 1 0 -s stdout -a 0x7f000000000

**Comment by koolzz** [comment]
Could you verify that one, there is technically no reason to use 0xf8 as mtcp is supposed to do it's own core managing

**Comment by XinShuYang** [comment]
./onvm/go.sh 1,2,3 1 0 -s stdout -a 0x7f000000000 can start the ONVM, but when I run the mtcp(epserver) it failed with  " Cause: There are no cores available for this NF".
Using ./onvm/go.sh 1,2,3 1 0xF8 -s stdout -a 0x7f000000000 doesn't have this problem.

**Comment by XinShuYang** [comment]
<img width="614" alt="Screen Shot 2019-04-12 at 10 58 34 AM" src="https://user-images.githubusercontent.com/25102428/56046753-f5bad480-5d11-11e9-9afe-bfcb3e10e2f3.png">

**Comment by koolzz** [comment]
As I see, yeah the standard core allocation does not make sense with this as we're not actually using the cores from the manager argument for mtcp but if there is nothing there the NF initialization complains. 

Thank you for testing this! I'll add some notes regarding the issue and submit the mtcp pr

**Comment by koolzz** [comment]
- [x] Submitted a PR for [mtcp](https://github.com/mtcp-stack/mtcp/pull/234)
- [ ] Still need a README note for onvm

**Comment by kevindweb** [comment]
Should have been closed with #197
