### ISSUE TITLE
Advanced Rings NF Shutdown on onvm_mgr Shutdown

### ISSUE THREAD

**Issue by koolzz** [sdnfv/openNetVM#105]
## Bug Report

**Current Behavior**
When we run Speed tester(or scaling NF) with advanced rings and then shut down onvm_mgr the speed tester NF doesn't properly shutdown.

**Expected behavior/code**
We would expect all NFs to shut down (even the advanced rings one)

**Steps to reproduce**
```sh
./go.sh 0,1,2 1 0xf0 -s stdout
./go.sh 5 -d 5 -a
```

**Possible Solution**
We need to properly handle messages for advanced rings (currently we just ignore all of them),

**Comment by nks5295** [comment]
Closed in #111
