### ISSUE TITLE
Wrong environment value error message

### ISSUE THREAD

**Issue by koolzz** [sdnfv/openNetVM#118]
*This issue describes a simple bug/improvement for the OpenNetVM code, and is a great way for **YOU** to get involved with improving this open source project! If you want to fix it, just create a pull request with the fix as detailed in the [Contributing](https://github.com/sdnfv/openNetVM/blob/develop/docs/Contributing.md) document. If you have questions, post here!*

----

## Bug Report

**Current Behavior**
When calling the `setup_environment.sh` script if the `ONVM_HOME` is not defined the message printed will say to set `ONVM_HOME` to an invalid location. 
See example bellow

```
koolzz@node2:/local/onvm/openNetVM/onvm/onvm_nflib$ export ONVM_HOME=""
koolzz@node2:/local/onvm/openNetVM/onvm/onvm_nflib$ ../../scripts/setup_environment.sh
Please export $ONVM_HOME and set it to /local/onvm/openNetVM/onvm/onvm_nflib
```

**Expected behavior/code**
We need to change the message to be the openNetVM directory.
```
koolzz@node2:/local/onvm/openNetVM/onvm/onvm_nflib$ export ONVM_HOME=""
koolzz@node2:/local/onvm/openNetVM/onvm/onvm_nflib$ ../../scripts/setup_environment.sh
Please export $ONVM_HOME and set it to /local/onvm/openNetVM
```

**Steps to reproduce**
See above ^

**Possible Solution**
There is a way to grab the script location in bash, using that and `../` we can obtain the root onvm dir.

**Comment by kevindweb** [comment]
This has been fixed, I just tried with the latest version of develop. `Please export $ONVM_HOME and set it to /users/kdeems/openNetVM`. Can I close this?

**Comment by koolzz** [comment]
@kevindweb are you sure?

```
yurchenko@nimbnode18:~/for_repo_managment/openNetVM-dev/onvm/onvm_mgr$ export ONVM_HOME=""
yurchenko@nimbnode18:~/for_repo_managment/openNetVM-dev/onvm/onvm_mgr$ echo $ONVM_HOME

yurchenko@nimbnode18:~/for_repo_managment/openNetVM-dev/onvm/onvm_mgr$ ../../scripts/setup_environment.sh 
Please export $ONVM_HOME and set it to /home/yurchenko/for_repo_managment/openNetVM-dev/onvm/onvm_mgr
```

**Comment by kevindweb** [comment]
I see the issue now, I can fix that later, and we can put it in the release.

**Comment by kevindweb** [comment]
Can I close this?

**Comment by koolzz** [comment]
@kevindweb  Well yeah you fixed it so go ahead :)
