### ISSUE TITLE
Running a NF using go.sh is not pinning the right core

### ISSUE THREAD

**Issue by madhura-a** [sdnfv/openNetVM#157]
## Bug Report

**Current Behavior**
Step 1: Run manager (./go.sh 0,1,2 0 0xf8 -s stdout -a 0x7f0000000)
Step 2: Run any network function using go.sh (./go.sh 1 -d 1)
Step 3: Check the core to which NF is pinned
 
The output of the taskset command shows that NF is pinned to core 0.

**Expected behavior/code**
Ideally, it should bind to core 4.
Running the NF using start_nf.sh is working as expected. 

**Environment**
 - onvm version:  latest

**Comment by twood02** [comment]
@dennisafa can you look into this?

@madhura-a can you tell us what version of ONVM you are using?

**Comment by dennisafa** [comment]
Hi @madhura-a 
I'm having a bit of trouble replicating your issue. I'm using the `master` branch version of ONVM. Using the 0xf8 bit mask specifies that you are registering cores 3-7 for NF usage:
<img width="582" alt="Screen Shot 2019-08-14 at 10 19 18 AM" src="https://user-images.githubusercontent.com/32916582/63028901-9f0b0600-be7d-11e9-8690-92ca80e3002b.png">

Running the simple_forward NF with the command you specified:
<img width="595" alt="Screen Shot 2019-08-14 at 10 28 30 AM" src="https://user-images.githubusercontent.com/32916582/63029293-4851fc00-be7e-11e9-974d-bbf27180c4fe.png">

I am seeing that it is binding to core 3 as expected:
<img width="860" alt="Screen Shot 2019-08-14 at 10 20 01 AM" src="https://user-images.githubusercontent.com/32916582/63028994-c7930000-be7d-11e9-81cb-48070f0ed064.png">

Please tell me a bit more about your environment, and if these are the steps you took to get to the bug.

**Comment by madhura-a** [comment]
Now just check whether the NF is actually running on core 3 or not.
I have used the command taskset -c -p <pid of NF>

![image](https://user-images.githubusercontent.com/37780565/63032065-b9bb9a00-bed2-11e9-8888-d51d06f74d50.png)

**Comment by madhura-a** [comment]
I think there is a problem with onvm_manager stats also. It always displays the first registered core.

**Comment by dennisafa** [comment]
> I think there is a problem with onvm_manager stats also. It always displays the first registered core.

By design, NF's are assigned to the first available core. Using htop I verified that the simple_forward NF is assigned to the proper core:
<img width="1278" alt="Screen Shot 2019-08-14 at 12 13 33 PM" src="https://user-images.githubusercontent.com/32916582/63037596-5fe4b100-be8d-11e9-9cfa-5f4a8fc5fae5.png">

Perhaps try htop and see if you get similar results.

**Comment by dennisafa** [comment]
I also tried with taskset. Please use taskset -c -p -a:
<img width="434" alt="Screen Shot 2019-08-14 at 12 26 16 PM" src="https://user-images.githubusercontent.com/32916582/63038317-e2ba3b80-be8e-11e9-9313-eb6bc370e058.png">

**Comment by madhura-a** [comment]
Taskset with -a option displayed the core correctly. Thank you.

But in stats, even though I changed the core to some other value using -l option, it still displays core as 3.
I have used the command as ./start_nf.sh speed_tester -l 5 -- -s -r 1 -- -d 1

![image](https://user-images.githubusercontent.com/37780565/63039129-46b92000-bee0-11e9-9b61-30f858b68ea4.png)

**Comment by dennisafa** [comment]
You must specify the manually assigned core flag -m: `-l 5 -- -s -m -r 1 -- -d 1`

**Comment by madhura-a** [comment]
Its working. Thank you.

**Comment by twood02** [comment]
@dennisafa @koolzz should we make it so that if you use `-l`, then `-m` is required?

**Comment by dennisafa** [comment]
@twood02 yes i agree. -l defaults to 0 when the ./go.sh script is called (see htop screenshot) 

We should change that - if -l is used then we assume the user is manually assigning a core, thus -m should be used as well.

**Comment by koolzz** [comment]
@twood02, @dennisafa 
Maybe we should just print a warning.
Technically a user may want to just use `-l` for dedicating a core which starts the NF (f.e when core 0 should be left completely unused as its running intensive computation), as it runs some basic dpdk startup before moving to a different core.
