### ISSUE TITLE
missing dependancies in install guide

### ISSUE THREAD

**Issue by base0x10** [sdnfv/openNetVM#161]
## Bug Report

**Current Behavior**
`install.sh, the script to configure and install dpdk relies on python2 in `/usr/env/python` which
is not by default installed on newer distros (with an eye to the eol in january).
Installing python is not a step in the install guide

**Expected behavior/code**
The install guide asks you to install python3

**Steps to reproduce**
try to install with guide on a fresh install of a new distro

**Environment**

- OS:  ubuntu 
- onvm version:  ?
- dpdk version:  ?
- other info:  ?

**Possible Solution**

Update install documentation

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by koolzz** [comment]
Hey @base0x10, good find, thank you for submitting an issue.
Do you possibly want to fix this issue and become a contributor?

**Comment by base0x10** [comment]
I'll make a PR for this issue and any other issues I find.  I don't have the permission to assign this issue to myself.  thanks

**Comment by pcodes** [comment]
@base0x10 any update on this?

**Comment by sreya519** [comment]
I can take a look at this issue and see what can be fixed.

**Comment by base0x10** [comment]
Thanks for taking this @sreya519
It looks like python2 may not be required for DPDK.  I am not sure if you want to add Python2 to the list of dependencies or to fix it to use python3 rather than python2.  See [here](https://doc.dpdk.org/guides/linux_gsg/sys_reqs.html) and [here](https://bugzilla.redhat.com/show_bug.cgi?id=1564215)

**Comment by twood02** [comment]
The solution is we should update our `scripts/*.py` to use python 3 and be sure that the install script adds python3 as a dependency.

Check if DPDK 18.11 requires python 2 for its user tools scripts. If so we should install both python2 and python3.

**Comment by twood02** [comment]
resolved by #221
