### ISSUE TITLE
Incorrect CloudLab Profile on Main Page

### ISSUE THREAD

**Issue by drbrents** [sdnfv/openNetVM#172]
## Bug Report

On the main openNetVM webpage (http://sdnfv.github.io/onvm/), the link to a CloudLab profile invalid.  The profile still exists, but will not start. 

It seems as though the link should be updated to this more recent profile: https://www.cloudlab.us/p/GWCloudLab/onvm

**Comment by dennisafa** [comment]
Thanks for pointing this out! We will update the link.
