### ISSUE TITLE
Some remaining questions on running performance tests

### ISSUE THREAD

**Issue by Wasdns** [sdnfv/openNetVM#18]
Hi, all. First, thank you for your great works!

Recently we are trying to test the performance of openNetVM SC on a commodity server. We have successfully built a simple service chain showed in [Linear NF Chain](https://github.com/sdnfv/openNetVM/blob/master/docs/Examples.md#linear-nf-chain) and planed to test the performance of this SC. In another PC, we established the DPDK environment and installed Pktgen. 

However, because we are lacking of experience in this aspect, we still have following problems:

(1)We are not capable to have two 10G NICs so that we use two original network adapters instead and have binded them to DPDK. But it seems to be not appropriate for Pktgen. Once we run the script "run-pktgen.sh", it reports the error like:

```
!PANIC!: *** Did not find any ports to use *** 
PANIC in pktgen_config_ports():
*** Did not find any ports to use ***
```

We have checked the binding status using "dpdk-devbind.py". Can we resolve this error? 

(2)So we consider other tools for performance testing, such as iperf and netperf. We plan to implement a topo like(assume we are using iperf):

```
PC1, with iperf client <---> the server which maintains openNetVM SC <---> PC2, with iperf server
```

Is it available in the scenario of openNetVM? Could you give us some suggestions on it?

Thank you very much!

**Comment by koolzz** [comment]
Hi @Wasdns 
Can you please provide the `sudo ./tools/dpdk_nic_bind.py --status` output. Maybe the NIC you're trying to use is not supported? Make sure the NICs are not blacklisted in the `run-pktgen.sh`

For part 2 if I understand you correctly the openNetVM machine will just forward incoming packets to the other machine, that can be done easily using our bridge NF. You could also chain more NFs if you want, but the bridge is the simplest for your setup.

**Comment by Wasdns** [comment]
Hi, @koolzz Thank you for your answer. 

-----

**"Can you please provide the `sudo ./tools/dpdk_nic_bind.py --status` output. Maybe the NIC you're trying to use is not supported? Make sure the NICs are not blacklisted in the `run-pktgen.sh`"**

-----

The output of `sudo ./tools/dpdk_nic_bind.py --status`:

```
Network devices using DPDK-compatible driver
============================================
0000:01:00.0 'NetXtreme II BCM5716 Gigabit Ethernet' drv=igb_uio unused=
0000:01:00.1 'NetXtreme II BCM5716 Gigabit Ethernet' drv=igb_uio unused=

Network devices using kernel driver
===================================
<none>

Other network devices
=====================
<none>

Crypto devices using DPDK-compatible driver
===========================================
<none>

Crypto devices using kernel driver
==================================
<none>

Other crypto devices
====================
<none>
```

The NICs are not in the blacklist of `run_pktgen.sh`.

-----

**"For part 2 if I understand you correctly the openNetVM machine will just forward incoming packets to the other machine, that can be done easily using our bridge NF. You could also chain more NFs if you want, but the bridge is the simplest for your setup."**

-----

I followed your instructions and start a service chain which is composed of a bridge and a monitor. And I created a topologic like: 

```
h1 <---> Server which runs openNetVM SC <---> h2
``` 

h1 runs scapy client(i.e.sending packets), and in contrast, h2 runs scapy server(i.e.receiving packets). And we applied the experiment here: [scapy-test: using scapy to execute openNetVM experiments](https://gist.github.com/Wasdns/91ddcf939e52ad983a66f8680e7ca1c1). 

Based on our observation, we conclude these results:
- (1)If we bind the two NIC ports to DPDK, we could not see any packets through wireshark, the monitor console and the console of PC2 server.
- (2)If we not bind the two NIC ports to DPDK, we could see lots of packets through wireshark, however, nothing output on both the monitor console and the console of PC2 server.

I don't know if the DPDK NIC ports would ignore the packets or not. Could you give me some advices on it? Thanks a lot!

**Comment by koolzz** [comment]
Hi, @Wasdns 
You won't see packets through wireshark when using DPDK NICs. You should see numbers in onvm_mgr and other NFs you have running.

How exactly are you running onvm_mgr? 
Are your machines directly connected?

**Comment by Wasdns** [comment]
Hello, @koolzz 
Thank you for your explanations. Exactly, I strictly followed the instructions of openNetVM documents [here](https://github.com/sdnfv/openNetVM/blob/master/docs/Examples.md#linear-nf-chain). The command that I used to run openNetVM manager:

```
$ ./onvm/go.sh 0,1,2,3,4 -s stdout
```

I don't know if we should start onvm_mgr with respect to [manager](https://github.com/sdnfv/openNetVM/tree/master/onvm#manager) instructions or not. Besides, all the machines are directly connected. 

Please point out our mistakes if we are wrong. Thank you very much!

**Comment by koolzz** [comment]
@Wasdns 
I see, the `./go.sh` script you're using expects port number argument.
The way you're running it is with ports disabled.

Try `$ ./onvm/go.sh 0,1,2,3,4 3 -s stdout` for 2 ports

**Comment by Wasdns** [comment]
@koolzz 

Thanks a lot. However, it occurs error when initialing the port 0. The error information like:

```
EAL: Detected 16 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:01:00.0 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:01:00.1 on NUMA socket 0
EAL:   probe driver: 8086:1521 net_e1000_igb
Creating mbuf pool 'MProc_pktmbuf_pool' [27648 mbufs] ...
Creating mbuf pool 'NF_INFO_MEMPOOL' ...
Creating mbuf pool 'NF_MSG_MEMPOOL' ...
Port 0 init ... 
Port 0 socket id 0 ... 
Port 0 Rx rings 1 ... 
EAL: Error - exiting with code: 1
  Cause: Cannot initialise port 0
```

I tried to debug this bug but found nothing. The output of `./dpdk/tools/dpdk-devbind.py --status`:

```
Network devices using DPDK-compatible driver
============================================
0000:01:00.0 'I350 Gigabit Network Connection' drv=igb_uio unused=
0000:01:00.1 'I350 Gigabit Network Connection' drv=igb_uio unused=

Network devices using kernel driver
===================================
<none>

Other network devices
=====================
<none>

Crypto devices using DPDK-compatible driver
===========================================
<none>

Crypto devices using kernel driver
==================================
<none>

Other crypto devices
====================
<none>
```

I have used `setup_environment.sh` to initial the environment and freed enough hugepages. How to resolve this situation? Thanks a lot!

**Comment by koolzz** [comment]
Looks like a hugepage issue, can you try the [hugepage fixes here](https://github.com/sdnfv/openNetVM/blob/master/docs/Install.md#troubleshooting)

**Comment by Wasdns** [comment]
**Additional:**

After rebooting, I tried to start onvm manager without binding the NIC ports to DPDK and it successfully started. However, the manager shows nothing received from the ports:

```
PORTS
-----



NFS
-------
NF  1 - rx:         0 rx_drop:         0 next:         0 drop:         0 ret:         0
        tx:         0 tx_drop:         0 out:          0 tonf:         0 buf:         0 
NF  2 - rx:         0 rx_drop:         0 next:         0 drop:         0 ret:         0
        tx:         0 tx_drop:         0 out:          0 tonf:         0 buf:         0
```

Moreover, the manager failed as soon as I rebinded these ports to DPDK.

**Comment by Wasdns** [comment]
@koolzz 
I have freed the hugepage and the output of `grep -i huge /proc/meminfo`:

```
AnonHugePages:      274432 kB
HugePages_Total:       2048
HugePages_Free:        2048
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
```

And I tried the instructions of Troubleshooting:

> The manager and NFs are not running, but something crashed without freeing hugepages.
   To fix this, please run `sudo rm -rf /mnt/huge/*` to remove all files that contain hugepage data.

The problem remained. I rebooted the machine and the same thing happened.

**Comment by twood02** [comment]
I think this is a NIC driver issue--if it will run without any ports configured that means the basic system (including huge pages) is working. If the Speed Tester example is working that is also a good sign. 

Have you tested whether the basic DPDK examples work (e.g. L2fwd)? We have only tested OpenNetVM with Intel-based 10GB NICs. If the DPDK examples run, then you can try to look at how they initialize ports compared to how we do it.

**Comment by nks5295** [comment]
I agree with @twood02.

@Wasdns I see two different NICs listed in your comments.  Can you check http://dpdk.org/doc/nics and make sure your NICs are supported by DPDK?

**Comment by Wasdns** [comment]
@twood02 @nks5295 Thank you for your helps! 

> "Have you tested whether the basic DPDK examples work (e.g. L2fwd)? We have only tested OpenNetVM with Intel-based 10GB NICs. If the DPDK examples run, then you can try to look at how they initialize ports compared to how we do it."

I create the same topologic as mentioned above. I have implemented the DPDK example "l2fwd" and used scapy to test. The test passed and both the packet receiver and the console which runs l2fwd could successfully reports the infomation, including the number of sent packets and received packets. 

> I see two different NICs listed in your comments. Can you check http://dpdk.org/doc/nics and make sure your NICs are supported by DPDK?

The first NIC list shows the NIC information of the server which runs Pktgen, and another one shows the NIC information of the server which maintains openNetVM SC. Exactly what we discussed above are two different tests: one for testing openNetVM by using Pktgen, another one for testing openNetVM by using scapy or iperf. I could see the abovementioned NIC types on the list at http://dpdk.org/doc/nics.

**Comment by Wasdns** [comment]
I don't resolve this problem currently on my server. I leverage another approach to run my experiments and I think I should close this issue. But I will report any process as soon as I try openNetVM. Thank you for your great efforts and kind helps!
