### ISSUE TITLE
Web Stats Documentation/Dependencies

### ISSUE THREAD

**Issue by kevindweb** [sdnfv/openNetVM#182]
## Bug Report

**Current Behavior**
Web Stats has a few documentation issues that need to be updated. Previously, I think when creating documentation, people, including me, already had certain dependencies that we didn't note.

**Expected behavior/code**
1) Without the `nettools` package, we cannot run the manager with onvm_web. It does not come with the base minimal install of Ubuntu 18.04, which is why I got the issue. 
2) `onvm_web` documentation is a little bit off on the `nodejs` and `npm` install process. Under the README `Build Installs` (at the bottom) it has directions on installing those tools. They are either outdated, or a bit wrong, specifically on the `npm` install. Screenshots for both issues are below.

**Steps to reproduce**
Provide command line instructions if possible.

**Environment**

- OS:  Ubuntu 18.04
- onvm version:  19.07
- dpdk version:  
- other info:  

**Possible Solution**
I do have the fix, it's not that difficult. Since it is not a vital programming bug, I labeled it `good first issue` so someone new can figure this out. It is a good way to learn what onvm_web is and how to build it if you're trying to update code. Please ask questions or ping me if you want to work on it.

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

![Screen Shot 2020-01-18 at 9 30 53 PM](https://user-images.githubusercontent.com/24497157/72673532-d045be80-3a39-11ea-8815-ee15d30cc316.png)
![Screen Shot 2020-01-18 at 9 32 14 PM](https://user-images.githubusercontent.com/24497157/72673544-008d5d00-3a3a-11ea-8ee7-b2e619a905a1.png)

**Comment by WilliamMaa** [comment]
I can fix this issue, can someone add me to it?
