### ISSUE TITLE
Pktgen DPDK Link Invalid

### ISSUE THREAD

**Issue by kevindweb** [sdnfv/openNetVM#187]
## Bug Report
[Pktgen Link](https://github.com/sdnfv/openNetVM/tree/master/tools/Pktgen) is not working in the Pktgen repo. Someone new should make a PR to fix this. If you want to do this, I would also say check all READMEs in the repo for validity. It would be a great help to make sure everything is up to date, as sometimes links die and need to be replaced. Please comment if you want to do this.

**Environment**

- OS:  
- onvm version:  Current
- dpdk version:  
- other info:  

**Possible Solution**

Fix the link in the README

**Comment by kevindweb** [comment]
@dennisafa @koolzz On another Pktgen note, I'm trying to run Pktgen from an Ubuntu 18 node, and it seems to be really finicky (from the cluster nodes). Sometimes it works and other times it doesn't even send packets through the NIC (nothing in TX). Do we need to update Pktgen or something? I'm pretty sure we need a higher version but someone can jump in here.

**Comment by dennisafa** [comment]
as discussed over slack - it is most likely a nimbnode cluster-specific issue. i confirmed that pktgen is working on the cloudlab nodes.

**Comment by catherinemeadows** [comment]
I can make a PR to update the Pktgen link and check all of the other links in the README's for validity.
