### ISSUE TITLE
Default Option for Core Masking and Error on Core Conflicts

### ISSUE THREAD

**Issue by EthanBaron14** [sdnfv/openNetVM#190]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Using the manager go.sh script requires multiple arguments. I'd like to simplify the default usage as much as possible. Further, the go.sh script currently allows users to overlap NF cores with manager cores. This could become problematic in that NFs might stop the manager from functioning properly.

**Describe the solution you'd like**
To accomplish this, I would add default values for the manager cores and the NF cores. With these defaults, the user would likely be prompted with a message during the manager startup indicating that they are using the default cores and could change that using an extra argument. Additionally, I would add an extra error message for the user if they are using manager and NF cores that overlap indicating the situation and strongly encouraging them to avoid that.

**Describe alternatives you've considered**
Considered stopping the run.sh script from running in the case of core conflicts. Likely will not implement this, as it might create an undesirable block for users running CPUs with fewer cores.

**Documentation, Integration Strategy**
Functionality of manager go.sh file will be largely unchanged with the exception of the fewer required argument count for execution. Installation guide would likely need updating but that would be it as far as documentation is concerned. For any assumed defaults, the user will be alerted that the script is using a default and that they could add a flag to manually change the parameters.

**Comment by EthanBaron14** [comment]
As discussed in our meeting on Monday, February 24, I will be working to implement these changes as part of my first contributions to the project. Anyone who has access can assign me.

**Comment by koolzz** [comment]
Sounds good, agree that stopping in case of overlapping is too much.
>> For any assumed defaults, the user will be alerted that the script is using a default and that they could add a flag to manually change the parameters.
Lets just make the core masks optional so if they're not provided we use the defaults.

**Comment by kevindweb** [comment]
@onvm can you just run?
