### ISSUE TITLE
HugePages Free Problem

### ISSUE THREAD

**Issue by asvcer** [sdnfv/openNetVM#20]
After I run openNetVM, I try to execute command `grep -i 'huge' /proc/meminfo` and find `HugePages_Free` is `0`. How can I free these used hugepage memory? I can find nothing in `/mnt/huge/` directory.

Then, I allocate another 1024 hugepages and run dpdk's simplest example `helloworld`, I find `HugePage_Free` is 1022 which indicates that 2 pages is leaked by `helloworld`.

There must be something wrong with my configuration or the program. Would you like to help me? Any suggestions is appreciated. Thank you very much!

**Comment by wen131** [comment]
I've suffer from the same problem, but I think it means DPDK handle the whole hugepages but didn't give it back to linux. Because I can still run a new DPDK application in that case.

**Comment by twood02** [comment]
Have you checked if there are still files left in your huge page directory? Sometimes if DPDK does not clean this up it will appear that huge pages are in use (but DPDK will reclaim them if you start it again).  If you are using our setup scripts, this will be in ` /mnt/huge`.  Try deleting any files leftover in that folder.

**Comment by asvcer** [comment]
Dear Tim,

On Ubuntu16.04, the hugepage files during run time is located in `/dev/hugepages/` rather than `/mnt/huge`. That's the cause.

Yours,
Shuo.
