### ISSUE TITLE
Replacing libc functions with DPDK functions

### ISSUE THREAD

**Issue by dennisafa** [sdnfv/openNetVM#201]
## Optimization

**Describe the solution you'd like**
We use libc functions in some parts of our NF's and manager code. This includes calls like `malloc` or `memcpy` or `strcpy`. DPDK [recommends](https://doc.dpdk.org/guides/prog_guide/writing_efficient_code.html) using their own functions, as they are optimized for the data plane environment. We'd like to identify points in the critical datapath where these calls occur and replace them.   

**Documentation, Integration Strategy**
I recommend looking at our example NF's, particularly the `pkt_handler` function as that will be called the most. Replace the libc function calls with DPDK function calls if possible, referring to the [API](https://doc.dpdk.org/api/) and note any performance benefits. It would also be worth looking at where these calls are used in the manager.

**Comment by bdevierno1** [comment]
I've been working with @kevindweb on #200 . I think I could switch the libc functions as well.
