### ISSUE TITLE
How many ports should I use?

### ISSUE THREAD

**Issue by asvcer** [sdnfv/openNetVM#21]
Dear Tim,

Sorry for this stupid question as I am quite dumb. I see from the manual that I need to pass a portmask option to onvm manager. Like this:

```
# onvm/go.sh 0,2,4,6,8,10,12 1 -s stdout
```

From the `onvm_args.c`, I see that `parse_portmask()` function accepts 0 port situation and it just shows a warning message. Thus I try the following command:
 
```
# onvm/go.sh 0,2,4,6,8,10,12 0 -s stdout
```

The `ONVM Manager` starts normally. In this situation, I wonder how to transfer packets to `ONVM`. Would you like to explain this? Thank you in advance!

Yours,
Shuo.

**Comment by twood02** [comment]
This depends what network functions you plan to run.  The port option controls which ports the ONVM manager will check for incoming packets.  If you specify 0, then ONVM will not check the NIC ports for incoming packets.  In this case the only way to have ONVM process any packets is to create them inside an NF.  For example, the Speed Tester NF creates a batch of packets and then forwards them to itself or another NF.

**Comment by asvcer** [comment]
Dear Tim,

Thank you for your reply. Have a good day!

Yours,
Shuo.
