### ISSUE TITLE
New version can't be compiled ?

### ISSUE THREAD

**Issue by veim** [sdnfv/openNetVM#22]
Hi, I find that the code is updated to v17.11, while install.md file is not. And "make" in onvm directory cannot make the project, with error:
`onvm_pkt.o: In function onvm_pkt_process_rx_batch:
onvm_pkt.c:(.text+0x97): undefined reference to onvm_pkt_enqueue_nf
`
So, place update the install.md file, or tell me how to compile the project, thank you very much!

**Comment by veim** [comment]
I solved this problem. Remove "inline" in declaration/definition of `onvm_pkt_enqueue_nf` in "onvm_nflib/onvm_pkt_common.h/c", then "make" in onvm directory is ok.
But I don't know why...

**Comment by twood02** [comment]
Can you report what gcc and OS version you are using so we can help diagnose this? Sounds like a change in compiler default settings.

**Comment by nks5295** [comment]
Here is my OS/Compiler info in which building ONVM works:

GCC:

```
▶ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

System:

```
▶ uname -a
Linux nimbnode38 3.16.0-77-generic #99~14.04.1-Ubuntu SMP Tue Jun 28 19:17:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

▶ lsb_release -r -v
No LSB modules are available.
Release:        14.04
```

Good catch to remove the `inline` there.  I think that the newer compiler versions are smart enough to detect that and cause an error.

**Comment by rskennedy** [comment]
Submitted [pull request #23 ](https://github.com/sdnfv/openNetVM/pull/23) that addresses this issue.

**Comment by veim** [comment]
Thank you for your quick response, here is my OS/Compiler info:
GCC:
`
gcc --version
gcc (Ubuntu 5.4.1-2ubuntu1~16.04) 5.4.1 20160904
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`
OS:
`
uname -a
Linux node1 4.8.8 #1 SMP Fri Nov 18 15:55:08 CST 2016 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -r -v
No LSB modules are available.
Release:	16.04
`
