### ISSUE TITLE
NF Runtime Errors

### ISSUE THREAD

**Issue by sreyanalla** [sdnfv/openNetVM#222]
## Bug Report
Runtime errors pertaining to `arp_response`, `load_generator`, `flow_table` NFs.

**Current Behavior**
The following errors are encountered:
- `arp_response` : NF exits due to "invalid command-line arguments" even if arguments are valid
- `load_generator` : NF exits because it "failed to obtain MAC address" with `-m`
- `flow_table` : hangs indefinitely after NF start up. NF need to be killed manually

**Expected behavior/code**
- `arp_response`:  NF should only exit for this reason if arguments are invalid 
- `load_generator` : MAC address should be properly obtained, allowing NF to run smoothly
- `flow_table` : NF should not hang -- if an error is identified, the NF should be killed automatically

**Steps to reproduce**
To reproduce, run each NF example as described in their respective [examples](https://github.com/sdnfv/openNetVM/tree/master/examples) folder. 
***Note:*** run `load_generator` using `-m` flag

**Environment**

- OS:  Ubuntu 18.04
- onvm version:  ONVM 20.05 (Current)

**Comment by catherinemeadows** [comment]
I can work on the fixes for the load_generator NF

**Comment by sreya519** [comment]
Looked into/ran `arp_response` and it seems like this issue no longer persists. If anyone else could validate this that would be great.

**Comment by catherinemeadows** [comment]
I was never able to replicate this issue, so I'm not sure what was happening. Maybe someone else can verify too
