### ISSUE TITLE
openNetVM NF manager crashed when running with more than 15 NFs 

### ISSUE THREAD

**Issue by maqiufang** [sdnfv/openNetVM#25]
I know that in your onvm_commom.h file,there has a max NF limit ,the value is 16. I adjusted this value to 128 , then the NF manager got an error:
EAL: Error - exiting with code: 1
Cause: Cannot initialise port 0
but setting for 64 is OK for 15 NFs. Then the NF manager would get crashed with more NFs......
Also, I changed the value of NF_INFO_CACHE to 0 in file /onvm/onvm_msg/onvm_init.h,since the default value (8) can only run 9 NFs in our server.By the way ,the server has 2x8 physical cores.

**Comment by twood02** [comment]
If you are still getting errors after adjusting the macros, please reopen this issue and we will look into it.
