### ISSUE TITLE
Destination used as NF Service ID in Scaling example with default callback

### ISSUE THREAD

**Issue by rohit-mp** [sdnfv/openNetVM#250]
## Bug Report

**Current Behavior**
While the usage [here](https://github.com/sdnfv/openNetVM/blob/27d9ed5d06ebcc987f36f8860b1935aaddc8cf1c/examples/scaling_example/scaling.c#L111) mentions that the functionality of the destination provided depends on the mode, I see that the when the NF is run in default callback mode, the destination is used for both for [forwarding the pkts](https://github.com/sdnfv/openNetVM/blob/27d9ed5d06ebcc987f36f8860b1935aaddc8cf1c/examples/scaling_example/scaling.c#L250) and for [setting the service ID of the threads spawned](https://github.com/sdnfv/openNetVM/blob/27d9ed5d06ebcc987f36f8860b1935aaddc8cf1c/examples/scaling_example/scaling.c#L232).

Because of the usage of destination as the service ID, it ends up creating a loop with the scaling NF forwarding the pkts to itself (even though I'd run another NF with a service ID as that of the destination passed to the scaling NF). The bridge NF stats in the screenshot attached are because of the pkts processed before the other threads are spawned which then process the pkts instead of the bridge NF.

**Expected behavior/code**
Normally, we'd expect all spawned threads of an NF to have the same session ID.

**Steps to reproduce**
Run manager:
```bash
./onvm/go.sh 0,2,4,6 0x3 0x1540 -s stdout -v
```
Run scaling NF:
```bash
cd examples/scaling_example
./go.sh 1 -n 3 -d 5
```
Run bridge NF:
```bash
cd examples/bridge
./go.sh 5
```

**Environment**

- OS:  Ubuntu
- onvm version:  20.05
- dpdk version:  -
- other info:  -

**Possible Solution**
The same is [done differently](https://github.com/sdnfv/openNetVM/blob/27d9ed5d06ebcc987f36f8860b1935aaddc8cf1c/examples/scaling_example/scaling.c#L436) with the advanced rings option and the same issue doesn't persist. Am I missing anything here?

**Additional context/Screenshots**
The below screenshot was taken after pktgen stopped sending the pkts
![Screenshot from 2020-07-25 15-47-34](https://user-images.githubusercontent.com/32365519/88454570-3f3f1c80-ce8e-11ea-9a64-2690ac778804.png)

**Comment by catherinemeadows** [comment]
This issue was resolved with PR [321](https://github.com/sdnfv/openNetVM/pull/321)
