### ISSUE TITLE
traditional DMA or DDIO

### ISSUE THREAD

**Issue by bahare70** [sdnfv/openNetVM#256]
Do receiving packets from NIC load into the memory or last level cache?
It means that openNetVM uses traditional DMA or DDIO?

Thanks in advance for your incorporation.

**Comment by twood02** [comment]
This is not something we have looked into.  OpenNetVM uses standard DPDK calls to retrieve packets from the NIC.  I *think* (but am not certain) that DPDK automatically makes use of DDIO technology if the hardware supports it, but you would have to check with the DPDK code to be sure about this.
