### ISSUE TITLE
Not enough cores to enable shared core support

### ISSUE THREAD

**Issue by JackKuo-tw** [sdnfv/openNetVM#268]
## Bug Report

**Current Behavior**

My ONVM is running in KVM + QEMU with 2 e1000 network adaptors.
Everything is fine except for the shared cores feature.

**Expected behavior/code**

Run the manager as normal.

**Steps to reproduce**

If this problem cannot be reproduced, I can provide the qcow2 image.

**Environment**

- OS:  Ubuntu 20.04
- onvm version:  v20.10
- dpdk version:  20.05.0

**Possible Solution**

None.

**Additional context/Screenshots**

![圖片](https://user-images.githubusercontent.com/21074047/97854067-ef48df00-1d33-11eb-9f35-d95424acb3e0.png)

Invoking manager command:

```sh
./go.sh -k 1 -n 0xF8 -s stdout -c
```

Invoking QEMU command:

```sh
sudo qemu-system-x86_64 -smp 8 -cpu Skylake-Server \
-m 4g -vga virtio -hda ubuntu20.04.qcow2 \
-nic tap,model=e1000 \
-nic tap,model=e1000 \
-accel kvm
```

**Comment by kevindweb** [comment]
@JackKuo-tw we updated our manager `go.sh` syntax, so if you just type `./go.sh`, you will see a few options. This one should fix your problem though.
`./go.sh -k 1 -n 0xF0 -m 0,1,2,3 -s stdout -c`. The manager explicitly needs more cores than usual for shared core, so this will give the manager 4 cores for example (`-m 0,1,2,3`). This worked for me on a normal non-qemu environment, hopefully it helps you.

**Comment by JackKuo-tw** [comment]
@kevindweb Thanks for your help. But another problem is that my NIC doesn't have 2 ports...


![圖片](https://user-images.githubusercontent.com/21074047/97946187-9c6b3800-1dc4-11eb-8950-daa8688198b9.png)

**Comment by kevindweb** [comment]
Can you take a screenshot of your dpdk setup? Do you have a port initialized? The command I sent is set for 1 port, so you might not have set up the port correctly? If you want to test without a NIC bound, just set `-k 0` instead.

**Comment by JackKuo-tw** [comment]
@kevindweb You're right. Afer with `-k 0` arg, it works! Thanks a lot!
And here is the DPDK setup:

![圖片](https://user-images.githubusercontent.com/21074047/97951864-86667300-1dd6-11eb-9a9d-f292b31ee3fe.png)
