### ISSUE TITLE
./onvm/go.sh 0,1,2,3 1 -s stdoutCause: Cannot initialise port 0

### ISSUE THREAD

**Issue by jiaxingChen** [sdnfv/openNetVM#27]
According to openNetVM/docs/Install.md, **1-18 step is successful, But at 19 step Run openNetVM manager, there is a issue** (I git clone -b develop latest version)
`root@cjx:/home/cjx/openNetVM# ./onvm/go.sh 0,1,2,3 1 -s stdout

EAL: Detected 12 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:04:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:04:00.1 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:06:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:105e net_e1000_em
EAL: PCI device 0000:06:00.1 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
**EAL:   probe driver: 8086:105e net_e1000_em
Creating mbuf pool 'MProc_pktmbuf_pool' [26112 mbufs] ...
Creating mbuf pool 'NF_INFO_MEMPOOL' ...
Creating mbuf pool 'NF_MSG_MEMPOOL' ...
Port 0 init ... 
Port 0 socket id 0 ... 
Port 0 Rx rings 1 ... 
EAL: Error - exiting with code: 1**
  **Cause: Cannot initialise port 0**`

I will appreciate it if you can give me some advices?

**Comment by twood02** [comment]
Can you test whether `./onvm/go.sh 0,1,2,3 0 -s stdout` starts correctly? This command sets the portmask to 0 so it will not try to use the NIC. 

We have not tested on the e1000 driver. Are you able to run DPDK examples successfully?

**Comment by jiaxingChen** [comment]
when  I run DPDK/examples/helloworld ,the result is:

```
sudo ./build/helloworld -l 0,1 -n 1
EAL: Detected 24 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:04:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:04:00.1 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:06:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:105e net_e1000_em
EAL: PCI device 0000:06:00.1 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:105e net_e1000_em
hello from core 1
hello from core 0
```
then ./onvm/go.sh 0,1,2,3 0 -s stdout
```
cjx@cjx:~/openNetVM$ ./onvm/go.sh 0,1,2,3 0 -s stdout
EAL: Detected 24 lcore(s)
EAL: Probing VFIO support...
EAL: PCI device 0000:04:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:04:00.1 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:06:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:105e net_e1000_em
EAL: PCI device 0000:06:00.1 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:105e net_e1000_em
WARNING: No ports are being used.
Creating mbuf pool 'MProc_pktmbuf_pool' [24576 mbufs] ...
Creating mbuf pool 'NF_INFO_MEMPOOL' ...
Creating mbuf pool 'NF_MSG_MEMPOOL' ...

Checking link statusdone
Default service chain: send to sdn NF
cur_index:1, action:2, destination:1

APP: Finished Process Init.
APP: 4 cores available in total
APP: 1 cores available for handling manager RX queues
APP: 2 cores available for handling TX queues
APP: 1 cores available for handling stats
APP: Core 1: Running TX thread for NFs 1 to 8
APP: Core 3: Running RX thread for RX queue 0
APP: Core 2: Running TX thread for NFs 9 to 15
APP: Core 0: Running master thread
```
then 
```
cjx@cjx:~/openNetVM$ ./examples/speed_tester/go.sh 5 1 1
EAL: Detected 24 lcore(s)
EAL: Probing VFIO support...
EAL: WARNING: Address Space Layout Randomization (ASLR) is enabled in the kernel.
EAL:    This may cause issues with mapping memory into secondary processes
EAL: PCI device 0000:04:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:04:00.1 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:1521 net_e1000_igb
EAL: PCI device 0000:06:00.0 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:105e net_e1000_em
EAL: PCI device 0000:06:00.1 on NUMA socket -1
EAL:   Invalid NUMA socket, default to 0
EAL:   probe driver: 8086:105e net_e1000_em
cur_index:1, action:2, destination:1

APP: Waiting for manager to assign an ID...
APP: Using Instance ID 3
APP: Using Service ID 1
APP: Finished Process Init
Creating 128 packets to send to 1

Client process 3 handling packets
Sending NF_READY message to manager...
[Press CTRL-C to quit]
```
result is 
```
PORTS
-----
NFS
-------
NF  1 - rx: 1478425888 rx_drop:         0 next:         0 drop:         0 ret:       128
        tx:         0 tx_drop:         0 out:          0 tonf: 1478425874 buf:         0 

Total packets: 2490000000 
TX pkts per second:  41064171 
Initial packets created: 128
```

**Comment by twood02** [comment]
OK, it looks like it is running correctly without any NIC ports. There must be a conflict with your NIC driver and how ONVM sets up the ports.

The e1000 driver is listed as a supported NIC: http://dpdk.org/doc/nics but it has some limitations. Possibly this is interfering with how we setup NIC ports in ONVM.

You should verify that the DPDK examples that initialize the port (e.g., l2fwd) work correctly for you. 

Unfortunately we do not have the hardware to test what is causing your issue. The problem is happening during port initialization. You could look at this code to try to narrow down the problem: https://github.com/sdnfv/openNetVM/blob/develop/onvm/onvm_mgr/onvm_init.c#L323

If you find the DPDK l2fwd example works correctly, then I suggest comparing how that code initializes the port against how ONVM init does it.

**Comment by madhura-a** [comment]
What I have understood is OpenNetVM manager uses one transmit ring buffer and one receive ring buffer. But in the file https://github.com/sdnfv/openNetVM/blob/develop/onvm/onvm_mgr/onvm_init.c#L323, in the function init_port(), tx_rings variable is assigned with MAX_NFS(i.e 16). Why it is so ? If I assign tx_rings a value 1, then the command ./onvm/go.sh 0,1,2,3 1 -s stdout is working fine. (for e1000 driver). Is this the right way ?

**Comment by twood02** [comment]
yes, this seems like a bug in our code. The number of TX_rings should be based on the number of TX threads, not on the maximum number of NFs.

We will look into making this change permanent.
