### ISSUE TITLE
Wrong NIC port in pktgen lua example

### ISSUE THREAD

**Issue by JackKuo-tw** [sdnfv/openNetVM#273]
## Bug Report

**Current Behavior**

In the [lua script](https://github.com/sdnfv/openNetVM/blob/d056dc8aba2d422525d06695a63a314920f9d607/tools/Pktgen/openNetVM-Scripts/pktgen-config.lua#L64), the first arg of `set_mac` is "1".

**Expected behavior/code**

First arg of `set_mac` is portlist, which should be "0" for consistence.
Otherwise, the command `page main` will see the `MAC Destination` is 00:00:00:00:00:00.

BTW, the in [wiki page about pktgen](https://github.com/sdnfv/openNetVM/wiki/Packet-generation-using-Pktgen) is outdated, `set_mac` should has 3 args.

**Environment**

- dpdk version:  20.10

**Comment by JackKuo-tw** [comment]
Oh, maybe I misunderstand it.
Which is a self-test script, not test with 2 nodes.

**Comment by dennisafa** [comment]
Do you need anymore assistance with this? What is your test environment?

**Comment by JackKuo-tw** [comment]
Nope, thanks.
