### ISSUE TITLE
Questions about the bridge example

### ISSUE THREAD

**Issue by strongcourage** [sdnfv/openNetVM#286]
Hi all,

I'm trying to modify the [bridge example](https://github.com/sdnfv/openNetVM/tree/master/examples/bridge) so that only packets from a given IP address will be sent from port 0 to port 1. Here there are 3 DPDK ports. By running the bridge example, I get the following result:
<img width="888" alt="Screenshot 2021-05-06 at 15 34 22" src="https://user-images.githubusercontent.com/9584484/117308801-25515200-ae82-11eb-8ae7-0f2a0ee3ce59.png">

I don't understand why TX of port 1 and RX of port 2 have those values (not 0). Does `meta->destination` correspond to the port ID, e.g., 0, 1, 2 ? In case where there are multiple ports, how can I only send packets to port 1 ? Thank you.

**Comment by JackKuo-tw** [comment]
What's your expectation & your code modification?

**Comment by strongcourage** [comment]
I'd like to implement a simple Load Balancer NF on VM1 that has 3 DPDK ports. The LB will send only packets from source IP1 to VM2, and only packets from source IP2 to VM3. On VM2 and VM3, there are different NFs that process those incoming packets.

<img width="1013" alt="Screenshot 2021-05-07 at 09 57 34" src="https://user-images.githubusercontent.com/9584484/117417497-b70c9e00-af1a-11eb-9809-4b312bc2ef7c.png">

I think I can adapt the bridge NF example to implement the LB, but it seems that it didn't work. Thank you.

```C
        struct rte_ipv4_hdr *ipv4_hdr;
        char ip_string[16];
        if (pkt->port == 0) {
                if (onvm_pkt_is_ipv4(pkt)) {
                    ipv4_hdr = onvm_pkt_ipv4_hdr(pkt);
                    onvm_pkt_parse_char_ip(ip_string, rte_be_to_cpu_32(ipv4_hdr->src_addr));
                    if (strncmp(ip_string, "192.168.", strlen("192.168.")) == 0) {
                        meta->destination = 1;
                        meta->action = ONVM_NF_ACTION_OUT;
                        RTE_LOG(INFO, APP, "Send packet from source IP %s to port %d\n", ip_string, meta->destination);
                    } else {
                        meta->destination = 2;
                        meta->action = ONVM_NF_ACTION_OUT;
                        RTE_LOG(INFO, APP, "Send packet from source IP %s to port %d\n", ip_string, meta->destination);
                    }
                } else {
                    meta->destination = 0;
                    meta->action = ONVM_NF_ACTION_DROP;
                }
        }
        else {
                meta->destination = 0;
                meta->action = ONVM_NF_ACTION_DROP;
        }
```

**Comment by strongcourage** [comment]
Thanks, Tim. It seems work when I set 2 different types of network adapter (Internal Network for DPDK-NIC2 and NAT Network for DPDK-NIC3) on VM1. If not, packets will be sent from port 0 to both ports 1 and 2.
