### ISSUE TITLE
Git submodules problem

### ISSUE THREAD

**Issue by luzhang92** [sdnfv/openNetVM#29]
when I use the comman 
`git submodule update`
it appear the following problem:
`
fatal: reference is not a tree: 091bae1beaeedd572be794eb04566903ba10bbcf
Unable to checkout 'd862f7a09ebc321ec54f8a910bcd410f5c4b8376' in submodule path 'dpdk'
Unable to checkout '091bae1beaeedd572be794eb04566903ba10bbcf' in submodule path 'tools/Pktgen/pktgen-dpdk'
`
How can fix it?

**Comment by twood02** [comment]
This sounds like your submodules got off track from the main repo.  If you `git pull develop` and then `git submodule update` again do you still get the same error?

**Comment by twood02** [comment]
If you are still having trouble with this please re-open the issue and let us know.
