### ISSUE TITLE
Regarding NIC information

### ISSUE THREAD

**Issue by tulika-agrawal** [sdnfv/openNetVM#30]
I want to ask a basic question. Actually, I'm facing some issue. So, I need some clearance about NIC.
1. Is it necessary to give 2 NICs to DPDK driver?
2. Is it necessary that NIC should be 10G?
Another question is related to CPU cores. I have 40 cores in my system, but when I'm checking the CPU architecture by the code corehelper.py, it is showing only 5 cores. So, how to allocate all the cores to ONVM so that more NFs can run?
Thanks in advance.

**Comment by koolzz** [comment]
1. There is no need to bind both NICs to the DPDK driver
2. The NIC doesn't have to be 10G but it has to be [supported by dpdk](https://dpdk.org/doc/nics)

Also I'm not sure why corehelper.py is only showing 5 cores, have you disabled hyperthreading?  As long as you give every NF a separate core and use at least 3 cores for the manager then everything should run. Make sure not to assign a core to both manager and a NF.

**Comment by tulika-agrawal** [comment]
Okay. Thanks a lot. And the script itself is disabling hyperthreading.

**Comment by nks5295** [comment]
The [setup_environment.sh](../blob/develop/scripts/setup_environment.sh) script should disable hyperthreading.

**Comment by tulika-agrawal** [comment]
Yeah, it is disabling. Thanks a lot. Maybe, it is some architecture issue.
