### ISSUE TITLE
Need help to do some changes to implement NFP

### ISSUE THREAD

**Issue by tulika-agrawal** [sdnfv/openNetVM#33]
Hello Sir,

I have completed my set up of OpenNetVM. It is working fine. Now, I am trying to implement NFP(Network Function Parallelism) in it (OpenNetVM is base in that work). I have to convert service chains into Service graphs to run NFs in parallel. If you have any idea, can you please give some insight to do this? Where should I do necessary changes? It will be helpful for me.

**Comment by twood02** [comment]
I am going to close this issue.  If you have further questions you can re-open it.  If you have code you want to share back to the project, create a pull request!

**Comment by tulika-agrawal** [comment]
Sure sir.
And I'm sorry, I forgot to close that issue.. Thanks a lot Sir
