### ISSUE TITLE
Error while setting up OpenNetVM

### ISSUE THREAD

**Issue by brajeshumrao84** [sdnfv/openNetVM#34]
Hello Sir,
I would like to setup OpenNetVM on my system. 

**My system configuration is as follows:**
--------------------------------------------
brajesh@brajesh:~$ lscpu
Architecture:                x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:                  Little Endian
CPU(s):                        8
On-line CPU(s) list:      0-7
Thread(s) per core:     2
Core(s) per socket:     4
Socket(s):                    1
NUMA node(s):           1
Vendor ID:                  GenuineIntel
CPU family:                6
Model:                       60
Model name:             Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
Stepping:                  3
CPU MHz:                 3890.390
CPU max MHz:         4000.0000
CPU min MHz:          800.0000
BogoMIPS:               7183.36
Virtualization:            VT-x
L1d cache:               32K
L1i cache:                32K
L2 cache:                256K
L3 cache:               8192K
NUMA node0 CPU(s):     0-7
-----------------------------------------

**My NIC Device is**
-------------------------------------------------------------------------
DeviceName:  Onboard LAN
	Subsystem: Dell Ethernet Connection I217-LM
	Kernel driver in use: e1000e
	Kernel modules: e1000e
----------------------------------------------------------------------

When I Configure and compile DPDK,  there is a problem, details are shown below:

brajesh@brajesh:~/openNetVM/scripts$ ./install.sh

----------------------------------------
ONVM Environment Variables:
----------------------------------------
RTE_SDK: /home/brajesh/openNetVM
RTE_TARGET: x86_64-native-linuxapp-gcc
ONVM_NUM_HUGEPAGES: 1024
ONVM_SKIP_HUGEPAGES: 
ONVM_SKIP_FSTAB: 
----------------------------------------
[sudo] password for brajesh: 
Compiling and installing dpdk in /home/brajesh/openNetVM/dpdk
Configuration done using x86_64-native-linuxapp-gcc
== Build lib
== Build lib/librte_compat
== Build lib/librte_eal
== Build lib/librte_eal/common
== Build lib/librte_eal/linuxapp
== Build lib/librte_eal/linuxapp/eal
== Build lib/librte_eal/linuxapp/igb_uio
== Build lib/librte_eal/linuxapp/kni
  Building modules, stage 2.
  MODPOST 1 modules
  Building modules, stage 2.
  MODPOST 1 modules
== Build lib/librte_ring
== Build lib/librte_cmdline
== Build lib/librte_timer
== Build lib/librte_cfgfile
== Build lib/librte_lpm
== Build lib/librte_acl
== Build lib/librte_kvargs
== Build lib/librte_jobstats
== Build lib/librte_metrics
== Build lib/librte_power
== Build lib/librte_meter
== Build lib/librte_mempool
== Build lib/librte_eventdev
== Build lib/librte_hash
== Build lib/librte_mbuf
== Build lib/librte_efd
== Build lib/librte_net
== Build lib/librte_cryptodev
== Build lib/librte_reorder
== Build lib/librte_ether
== Build lib/librte_sched
== Build lib/librte_vhost
== Build lib/librte_gro
== Build lib/librte_ip_frag
== Build lib/librte_bitratestats
== Build lib/librte_latencystats
== Build lib/librte_distributor
== Build lib/librte_pdump
== Build lib/librte_kni
== Build lib/librte_port
== Build lib/librte_table
== Build lib/librte_pipeline
== Build buildtools
== Build buildtools/pmdinfogen
== Build drivers
== Build drivers/bus
== Build drivers/mempool
== Build drivers/event
== Build drivers/event/skeleton
== Build drivers/mempool/ring
== Build drivers/mempool/stack
== Build drivers/event/sw
== Build drivers/event/octeontx
== Build drivers/crypto
== Build drivers/net
== Build drivers/crypto/scheduler
== Build drivers/crypto/null
== Build drivers/net/ark
== Build drivers/net/af_packet
== Build drivers/net/avp
== Build drivers/net/bonding
== Build drivers/net/cxgbe
== Build drivers/net/e1000
== Build drivers/net/ena
== Build drivers/net/enic
== Build drivers/net/failsafe
== Build drivers/net/fm10k
== Build drivers/net/i40e
== Build drivers/net/ixgbe
== Build drivers/net/liquidio
== Build drivers/net/nfp
== Build drivers/net/bnxt
== Build drivers/net/null
== Build drivers/net/qede
== Build drivers/net/ring
== Build drivers/net/sfc
== Build drivers/net/tap
== Build drivers/net/thunderx
== Build drivers/net/virtio
== Build drivers/net/vmxnet3
== Build drivers/net/kni
== Build drivers/net/vhost
== Build app
== Build app/test-pmd
== Build app/proc_info
== Build app/pdump
== Build app/test-eventdev
== Build app/test-crypto-perf
Build complete [x86_64-native-linuxapp-gcc]
Configuration done using x86_64-native-linuxapp-gcc
== Build lib
== Build lib/librte_compat
== Build lib/librte_eal
== Build lib/librte_eal/common
== Build lib/librte_eal/linuxapp
== Build lib/librte_eal/linuxapp/eal
== Build lib/librte_eal/linuxapp/igb_uio
== Build lib/librte_eal/linuxapp/kni
  Building modules, stage 2.
  Building modules, stage 2.
  MODPOST 1 modules
  MODPOST 1 modules
== Build lib/librte_ring
== Build lib/librte_cmdline
== Build lib/librte_timer
== Build lib/librte_cfgfile
== Build lib/librte_lpm
== Build lib/librte_kvargs
== Build lib/librte_acl
== Build lib/librte_jobstats
== Build lib/librte_metrics
== Build lib/librte_power
== Build lib/librte_meter
== Build lib/librte_mempool
== Build lib/librte_eventdev
== Build lib/librte_hash
== Build lib/librte_mbuf
== Build lib/librte_efd
== Build lib/librte_reorder
== Build lib/librte_net
== Build lib/librte_cryptodev
== Build lib/librte_ether
== Build lib/librte_sched
== Build lib/librte_vhost
== Build lib/librte_ip_frag
== Build lib/librte_gro
== Build lib/librte_bitratestats
== Build lib/librte_latencystats
== Build lib/librte_distributor
== Build lib/librte_kni
== Build lib/librte_pdump
== Build lib/librte_port
== Build lib/librte_table
== Build lib/librte_pipeline
== Build buildtools
== Build buildtools/pmdinfogen
== Build drivers
== Build drivers/bus
== Build drivers/mempool
== Build drivers/event
== Build drivers/event/skeleton
== Build drivers/event/octeontx
== Build drivers/event/sw
== Build drivers/mempool/ring
== Build drivers/mempool/stack
== Build drivers/net
== Build drivers/crypto
== Build drivers/net/af_packet
== Build drivers/net/avp
== Build drivers/net/ark
== Build drivers/net/cxgbe
== Build drivers/crypto/scheduler
== Build drivers/net/ena
== Build drivers/net/e1000
== Build drivers/net/bonding
== Build drivers/crypto/null
== Build drivers/net/enic
== Build drivers/net/failsafe
== Build drivers/net/fm10k
== Build drivers/net/i40e
== Build drivers/net/liquidio
== Build drivers/net/ixgbe
== Build drivers/net/nfp
== Build drivers/net/bnxt
== Build drivers/net/null
== Build drivers/net/qede
== Build drivers/net/ring
== Build drivers/net/sfc
== Build drivers/net/thunderx
== Build drivers/net/tap
== Build drivers/net/virtio
== Build drivers/net/vmxnet3
== Build drivers/net/kni
== Build drivers/net/vhost
== Build app
== Build app/test-pmd
== Build app/proc_info
== Build app/test-crypto-perf
== Build app/pdump
== Build app/test-eventdev
Build complete [x86_64-native-linuxapp-gcc]
Installation cannot run with T defined and DESTDIR undefined
Configuring 1024 hugepages with size 1048576
huge /mnt/huge hugetlbfs defaults 0 0
Mounting hugepages
Creating 1024 hugepages
Configuring environment
Loading uio kernel modules
insmod: ERROR: could not insert module igb_uio.ko: Required key not available

Please resolve the problem.

**Comment by mdasari823** [comment]
Hi, I am facing the same issue. I have my RTE_SDK path to dpdk though.

**Comment by nks5295** [comment]
The `igb_uio.ko` driver is built with DPDK.  That is DPDK's UIO driver that leverages the Linux UIO module.  DPDK needs this as it controls I/O from NICs from userspace.  Our utility scripts (`install.sh` and `setup_environment.sh`) describe the DPDK build process and `igb_uio.ko` installation process.

Can you please post the output of the following commands?
```
echo $RTE_SDK
echo $RTE_TARGET
uname -a
hugeadm --list-all-mounts --pool-list
lspci | grep Ethernet
sudo modprobe uio && lsmod | grep uio
lscpu
```

**Comment by mdasari823** [comment]
Hi Neel, thank you very much for your response. Please find the output of above commands.
![screenshot from 2018-05-11 16-57-30](https://user-images.githubusercontent.com/21373364/39946586-b36c9d26-553c-11e8-8a59-34ad032c345c.png)

**Comment by kevindweb** [comment]
Can we assume this is no longer a problem? If it's still an issue, how can we clean this up?

**Comment by twood02** [comment]
I suspect it has been resolved by our updates.  I will close the issue and it can be reopened if it comes up again.
