### ISSUE TITLE
the cpu core ultilization

### ISSUE THREAD

**Issue by luzhang92** [sdnfv/openNetVM#37]
When I run the openNetVM manager, it requires 4 cores. But when I use the command 'top', why I only see the manager occupy the cpu by 300%, not 400%

**Comment by nks5295** [comment]
ONVM's core usage looks like this: 1 core for initialization and then displaying stats, 1 core for Rx, and N cores for Tx.  We need at least 1 Tx core.

When the manager first starts up, the core for initialization and stats display will spin around 100%.  Once the manager is initialized and the core becomes solely for displaying stats, that thread becomes way less resource intensive and the core will be utilized very little.
The Rx and Tx threads however will always spin at around 100%.

If you're using 4 cores, then the 300% utilization is expected.
