### ISSUE TITLE
Pktgen is not starting on a machine with 6 cores

### ISSUE THREAD

**Issue by madhura-a** [sdnfv/openNetVM#39]
Hello sir,
I am trying to run pktgen in a machine which has 6 cores. So I made changes in the file **run-pktgen.sh** by giving coremask as 003f. But pktgen is unable to transmit the packet. Is it because of cores or some other reason? NIC I am using is IC10 and is supported in dpdk.

**Comment by twood02** [comment]
We can't provide support for pktgen, but you can try posting in the DPDK mailing list.

You can try updating the version of pktgen. Some pktgen docs are here and may help: http://pktgen-dpdk.readthedocs.io/en/latest/getting_started.html

There are also other packet generators you can consider using such as: https://github.com/emmericp/MoonGen or https://trex-tgn.cisco.com/
