### ISSUE TITLE
Speed tester should be able to create 0 packets

### ISSUE THREAD

**Issue by twood02** [sdnfv/openNetVM#46]
*This issue describes a simple bug/improvement for the OpenNetVM code, and is a great way for **YOU** to get involved with improving this open source project! If you want to fix it, just create a pull request with the fix as detailed in the [Contributing](https://github.com/sdnfv/openNetVM/blob/develop/docs/Contributing.md) document. If you have questions, post here!*

----

Currently the speed tester NF requires a `-c` parameter of 1 or greater, causing it to create at least 1 packet. This is unnecessary in cases where you are running a chain of speed testers (only 1 NF in the chain needs to create packets) and is unnecessary when using the speed tester to measure throughput with packets generated by another source (note that those packets will still need to have the `SPEED_TESTER_BIT` set or the packets will be dropped).

Simple fix: 
 - Change this condition to only produce an error if parameter is `< 0`
 - Print a warning message that no packets were created

**Comment by ratnadeepb** [comment]
It seems that making this change is trivial but due to the 
packet_number? packet_number : MAX_PKT_NUM
test, the number of initial packets become 128 when -c is 0. I can change this, but have not figured the effect of this change yet. Can someone please provide some guidance?

**Comment by twood02** [comment]
Yes, you may have to change that logic. It is OK if you need to change some other aspects of the program.

**Comment by twood02** [comment]
This was resolved by #56
