### ISSUE TITLE
The new DPDK version 17.08 cannot use the binded NICs

### ISSUE THREAD

**Issue by lilishan9248** [sdnfv/openNetVM#47]
Hi, 

The new version of openNetVM is based on dpdk version 17.08. 
I have finished the installment of dpdk and binded NIC ports to DPDK. The NIC devices are Intel 82599.
However, I meet the following error when running the manager. 

EAL: Detected 12 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:82:00.0 on NUMA socket 1
EAL:   probe driver: 8086:154d net_ixgbe
EAL: Requested device 0000:82:00.0 cannot be used
EAL: PCI device 0000:82:00.1 on NUMA socket 1
EAL:   probe driver: 8086:154d net_ixgbe
EAL: Requested device 0000:82:00.1 cannot be used
WARNING: requested port 0 not present - ignoring
WARNING: requested port 1 not present - ignoring
Creating mbuf pool 'MProc_pktmbuf_pool' [24576 mbufs] ...
Creating mbuf pool 'NF_INFO_MEMPOOL' ...
Creating mbuf pool 'NF_MSG_MEMPOOL' ...

The binded NIC ports cannot be used. I also check the helloworld example in the dpdk 17.08. The same error occurs. 

EAL: Detected 12 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: PCI device 0000:82:00.0 on NUMA socket 1
EAL:   probe driver: 8086:154d net_ixgbe
EAL: Requested device 0000:82:00.0 cannot be used
EAL: PCI device 0000:82:00.1 on NUMA socket 1
EAL:   probe driver: 8086:154d net_ixgbe
EAL: Requested device 0000:82:00.1 cannot be used
hello from core 1
hello from core 0

Therefore, the openNetVM cannot receive packets from other servers. Have you ever met the above errors? Could you please give me some guidance to solve it? Thanks a lot!

Best Regards,
Lishan

**Comment by twood02** [comment]
If you have solved this on your own can you post your solution so that others who face the same issue can get help? (looks like either a huge page configuration issue or the NICs were not bound to DPDK correctly)

**Comment by lilishan9248** [comment]
I have solved this issue by reinstalling DPDK (version 17.08). 
This issue is caused by DPDK, not openNetVM. The NICs were correctly bounded to DPDK. 
I still know the real reason for the error.
