### ISSUE TITLE
Low performance with OpenNetVM

### ISSUE THREAD

**Issue by lapd-viosoft** [sdnfv/openNetVM#6]
Hi all,
I'm trying to do performance evaluation with OpenNetVM with simple application (examples/bridge). The test is RFC2544 throughput testing. However the result (Zero-Loss point) is quite low for small packet size(compare to l2fwd-dpdk example)

| Packet size(bytes)       | OpenNetVM-Bridge app(% of 10GbE)           | Intel DPDK-L2FWD app(% of 10GbE)  |
| ------------- |:-------------:| -----:|
| 64      | 28 | 80 |
| 128      | 51 |   100|
| 256 | 94 | 100 |
| 512 | 100| 100 |
The setup topo is.
![bridgeapp](https://cloud.githubusercontent.com/assets/17825933/15011088/141182e4-121a-11e6-8957-a5a8f8475dbc.png)
The connection between two server is cross-over (no switch).
Two servers is Dell R730, 192Gb RAM and 24 cores of each.
The NICs are on socket 0 with cores 0,2,4,6,8,10,12,14...,22. All cores are isolated by declaration in the grub.
Manager: ./go.sh 0,2,4,6,8,10,12 3
Bridge app: ./go 14 1

Could you please give me some hints to get high test result?
Thank and Best Regards
Lapd

**Comment by lapd-viosoft** [comment]
Hi all,
Checking more log by calling rte_eth_stats_get(port_id, &eth_stats) I can see the received error packet stats:

```sh
  struct rte_eth_stats eth_stats;
        unsigned i;
        for (i = 0; i < rte_eth_dev_count(); i++) {
                rte_eth_stats_get(i, &eth_stats);
                printf("\nPort %u stats:\n", i);
                printf(" - Pkts in:   %"PRIu64"\n", eth_stats.ipackets);
                printf(" - Pkts out:  %"PRIu64"\n", eth_stats.opackets);
                printf(" - In Errs:   %"PRIu64"\n", eth_stats.ierrors);
                printf(" - Out Errs:  %"PRIu64"\n", eth_stats.oerrors);
                printf(" - Mbuf Errs: %"PRIu64"\n", eth_stats.rx_nombuf);
        }
```
```sh
Port 0 stats:
 - Pkts in:   155440503
 - Pkts out:  155264785
 - In Errs:   254299497
 - Out Errs:  0
 - Mbuf Errs: 0

Port 1 stats:
 - Pkts in:   155440561
 - Pkts out:  155264631
 - In Errs:   254299663
 - Out Errs:  0
 - Mbuf Errs: 0
```
All packets sent by traffic generator are the same format.
Is there a case that the OpenNetVM Manager process is not fast enough to receive packets, packets are marked as error?
Lapd

**Comment by lapd-viosoft** [comment]
Hi all, 
I'm able to get high results now after
- Add one more core for RX on onvm_mgr/init.h
- Increase RX/TX and Ring buffer size onvm_mgr/init.c
#define RTE_MP_RX_DESC_DEFAULT 2048
#define RTE_MP_TX_DESC_DEFAULT 2048
#define CLIENT_QUEUE_RINGSIZE 2048
Lapd

**Comment by twood02** [comment]
@lapd-viosoft yes, that is the right approach. We will be updating the docs with this kind of tuning advice.
