### ISSUE TITLE
Env var check

### ISSUE THREAD

**Issue by koolzz** [sdnfv/openNetVM#61]
*This issue describes a simple bug/improvement for the OpenNetVM code, and is a great way for **YOU** to get involved with improving this open source project! If you want to fix it, just create a pull request with the fix as detailed in the [Contributing](https://github.com/sdnfv/openNetVM/blob/develop/docs/Contributing.md) document. If you have questions, post here!*

----

We should add an `ONVM_HOME` environment variable check to `onvm/onvm_nflib/Makefile`. If the variable is not defined we should print that and exit as installation will fail if its not defined. Same as we do with `RTE_SDK`

The variable is accessed [here](https://github.com/sdnfv/openNetVM/blob/develop/onvm/onvm_nflib/Makefile#L55) 

This is low priority and can be a good first issue if we want more of those.

**Comment by twood02** [comment]
This only becomes relevant once the 18.11 release changes get merged, but it will be a #good_first_issue after that.
