### ISSUE TITLE
OpenNetVM manager will crash if a NF's service id was assigned greater than or equal to 16

### ISSUE THREAD

**Issue by lyuxiaosu** [sdnfv/openNetVM#64]
To reproduce this bug, just start OpenNetVM manager and any NF with service id 16 or greater than 16, the manager will crash immediately.  The reason is the following:

The array of "mz_services" was allocated only 16 entries because currently we support 16(actually is 15, 0 is reserved) NFs. But when the NF send a NF_READY message to the manager with the service id, the manager will directly access mz_services[service_id] without checking if the service_id is less than 16, which causes manager crash.The same access operation also apply to the "nf_per_service_count", which is also a 16 length array.

**Comment by koolzz** [comment]
@twood02 seems like a good first issue?

Its just adding a check for service id, probably here: https://github.com/sdnfv/openNetVM/blob/develop/onvm/onvm_mgr/onvm_nf.c#L185

**Comment by koolzz** [comment]
@lyuxiaosu are you using the latest version of onvm? The bug is most likely still there but the 
 MAX_SERVICES was increased to 32.

**Comment by lyuxiaosu** [comment]
@koolzz Yes, I think I used the old version of onvm, so to reproduce this bug on the latest version, need to assign a service id with 32 or greater than 32. Thanks let me know.

**Comment by dennisafa** [comment]
Shouldn't it be `if (nf_id >= MAX_SERVICES)` rather than `if (nf_id >= MAX_NFS)` if we'd like to avoid going past 32?

**Comment by lyuxiaosu** [comment]
@dennisafa I think that won't resolve this problem because nf_id is the id of a NF, whose maximum value should be less than MAX_NFS ( the maximum number of NFs), so,  `if (nf_id >= MAX_NFS)` is to check the validation of nf_id, which is correct. But it lacks the part of checking the validation of `nf_info->service_id`. The maximum of services types is defined by macro `MAX_SERVICES`, which is 32. `nf_info->service_id ` should not exceed `MAX_SERVICES`. To fix this problem, we can add the checking validation logic for  `nf_info->service_id` after checking the validation of nf_id.

**Comment by twood02** [comment]
solved by #66.
