### ISSUE TITLE
Help with packetgen

### ISSUE THREAD

**Issue by adilahmad17** [sdnfv/openNetVM#8]
Hi,

I was getting errors when trying to use the packetgen instead of the provided speed-tester app to measure throughput. Can someone please add a readme with a simple example illustrating how that will work?

Thanks,
Adil

**Comment by sameergk** [comment]
Hi Adil,
What is your setup? Are you trying to run the packet-gen on the same node as that of OpenNetVM?  
I don't think it is possible to run OpenNetVM-Manager and Packetgen on the same nodes, but you can run them on two different nodes that are connected with each other. 
Let me know, if you run into any issues running packetgen and openNetVM on two different nodes.

**Comment by nks5295** [comment]
[This document](https://github.com/sdnfv/openNetVM/blob/master/docs/pktgen.md) walks through setting up and using Pktgen.

Pktgen must be ran on a different machine from ONVM.  For example, hostA runs ONVM and hostB runs Pktgen.

The Speed Tester NF is not to be used with Pktgen, instead, try using the Basic Monitor NF.

**Comment by adilahmad17** [comment]
Oh, I was using the same node to run the packetgen. Let me try with a different node. Thanks for sharing that document. I'll tell you guys if I run into problems.

Thanks!

**Comment by twood02** [comment]
I'll close this issue, but if you have more issues let us know.
