### ISSUE TITLE
Problems when running example NF test_flow_dir

### ISSUE THREAD

**Issue by Zhengzl15** [sdnfv/openNetVM#9]
Hi,

I was getting problems when trying to run NF test_flow_dir. 

When sending packets to openNetVM, this NF outputs nothing but crashed(even no any error prompts). And I found that `tbl_index = rte_hash_lookup_with_hash(table->hash, (const void *)&key, pkt->hash.rss);` in `int onvm_ft_lookup_pkt(...)` works wrong. But why? Is it some special mechanism of rte_hash in DPDK or bug of openNetVM? 

Can someone give me some suggestions to make it work correctly?

Thanks,
Zhilong

**Comment by twood02** [comment]
What version of DPDK are you using? Did you get DPDK yourself, or are you using the version that gets put in git sub module if you follow our install instructions. 

This sounds like a bug that we've seen caused in older versions of DPDK which do not correctly support hash tables in multi process programs (which ONVM requires). The recent versions of DPDK are supposed to have patched this (untested with ONVM), or our DPDK repo has a fixed version.

**Comment by Zhengzl15** [comment]
Hi,

I am using the version that gets from git sub module, which follows the installation document(it should be v2.2.0). Is it the correct version?

**Comment by twood02** [comment]
yes, I think that is the right version.  How are you sending packets? (real traffic? pktgen?)

**Comment by Zhengzl15** [comment]
I used pktgen to generate packets. `onvm_flow_dir_get_pkt()` works correctly in `onvm_pkt_process_rx_batch()`, however it cannot lookup any key in a NF.

**Comment by twood02** [comment]
The flow director matches packets by looking at the IP and TCP headers, so the traffic you are generating with pktgen may be missing the fields needed to be considered a flow.  That should result in all of the packets getting matched to the default flow / default service chain.

In general, the flow director (and this example) are only intended for use with standard TCP flows.  I'm not sure why it is crashing though.  We will take a look as well (@nks5295 @phil-lopreiato @zhangwei1984 @Grace-Liu)

**Comment by Zhengzl15** [comment]
Factly, I initialized "ft" with a key(an ipv4_5tuple header) and entry. The key is the 5 tuple header of packets pktgen generates. And `onvm_flow_dir_get_pkt ()` in onvm_mgr can get the entry with incoming packets instead of the default service chain(**Debugging with printf()**). Also, it can get correct entry when calling `onvm_flow_dir_get_pkt ()` in `init()` after adding the key and entry.     

Moreover, calling `onvm_flow_dir_add_key()` in the NF process also crashes, though.

It seems like everything in onvm_mgr process works well but in the NF process it goes awry.

It is weird.

**Comment by Zhengzl15** [comment]
Hi,

I replaced the default DPDK version in your repo with the latest official release(v16.11), then the problem went away.  

Thanks for your kind help!
